# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Turnup Works
tagline:             'Business development for start-ups and growth business'
description:         ''
url:                 http://turnupworks.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              James Holland
  url:               https://github.com/jholl/
  email:             holland.jb@gmail.com

# Custom vars
version:             1.0.0
